name: Build and Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Setup Node.js (use the version you require)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # 3. Install dependencies
      - name: Install Dependencies
        run: npm install --force
        env:
            NODE_OPTIONS: "--max_old_space_size=4096"

      # 4. Build the Angular App in production mode
      - name: Build Angular App
        run: npm run build -- --configuration production --aot

      # 5. Deploy to Firebase Hosting using the Firebase Extended action
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"          # Auto-generated by GitHub
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"  # Your service account JSON key
          channelId: live  # Use "live" to deploy to production; you can also use preview channels
